spring.application.name=bv2-projeto-software-uepg

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bv2}
spring.datasource.username=${DB_USERNAME:bv2}
spring.datasource.password=${DB_PASSWORD:bv2}
spring.datasource.driver-class-name=org.postgresql.Driver

