-- =============================================================================
-- V10 — notificacoes
-- Log de execução dos envios de WhatsApp: cada linha é uma mensagem disparada
-- pela mudança de status de uma OS, com o texto que de fato foi ao cliente.
-- Depende de: ordens_servico e enum status_os (V7), clientes (V5).
-- =============================================================================

CREATE TYPE status_notificacao AS ENUM ('PENDENTE', 'ENVIADO', 'FALHOU');

CREATE TABLE notificacoes (
    id                  BIGINT                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_ordem_servico    BIGINT                  NOT NULL,
    id_cliente          BIGINT                  NOT NULL,

    -- Texto já renderizado (placeholders substituídos). 1000 e não 500 como o
    -- template, porque a substituição aumenta o texto.
    conteudo            VARCHAR(1000)           NOT NULL,

    status              status_notificacao      NOT NULL DEFAULT 'PENDENTE',
    tentativas          INTEGER                 NOT NULL DEFAULT 0,
    data_envio          TIMESTAMP,
    criado_em           TIMESTAMP               NOT NULL DEFAULT NOW(),

    -- Status da OS que disparou o envio. Coluna e não FK para
    -- templates_notificacao: é log e precisa sobreviver à edição do template.
    status_os           status_os               NOT NULL,

    CONSTRAINT pk_notificacao PRIMARY KEY (id),
    CONSTRAINT fk_notificacao_ordem_servico
        FOREIGN KEY (id_ordem_servico)
        REFERENCES ordens_servico (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_notificacao_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_notificacao_tentativas
        CHECK (tentativas >= 0)
);

-- As duas consultas de GET /notificacoes filtram exatamente por essas FKs.
CREATE INDEX idx_notificacoes_ordem_servico ON notificacoes (id_ordem_servico);
CREATE INDEX idx_notificacoes_cliente       ON notificacoes (id_cliente);
