--- Marca quando a senha mudou, para invalidar os tokens JWT emitidos antes disso.
--- Nulo significa "nunca trocou", e nao "trocou na epoca zero": com NULL os tokens
--- ja emitidos continuam validos apos o deploy, em vez de deslogar todo mundo de
--- uma vez sem motivo.
---
--- Gravado truncado a segundos pelo Java: o iat do JWT e em segundos e este
--- TIMESTAMP guarda microssegundos. Sem truncar, a comparacao erraria por
--- arredondamento e derrubaria sessoes legitimas de forma intermitente.
ALTER TABLE usuarios ADD COLUMN senha_alterada_em TIMESTAMP;

--- Guarda o SHA-256 do token, nunca o token: vazamento do banco nao pode virar
--- tomada de contas. SHA-256 e nao BCrypt por dois motivos — o token ja nasce com
--- 256 bits de entropia (nao precisa de key stretching) e precisa ser buscavel por
--- igualdade, o que o sal do BCrypt impediria sem varrer a tabela inteira.
CREATE TABLE tokens_recuperacao_senha (
    id          BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  BIGINT      NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expira_em   TIMESTAMP   NOT NULL,
    usado_em    TIMESTAMP,
    criado_em   TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_token_recuperacao_senha PRIMARY KEY (id),
    CONSTRAINT uq_token_recuperacao_senha_hash UNIQUE (token_hash),
    CONSTRAINT fk_token_recuperacao_senha_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT
);

--- usado_em nulo = pendente. O historico fica: da para auditar quantos links foram
--- pedidos e quais viraram troca de senha de fato.
CREATE INDEX idx_tokens_recuperacao_usuario ON tokens_recuperacao_senha (id_usuario);
