-- =============================================================================
-- V1 — usuarios
-- Quem faz login no sistema: a equipe BV2 (MASTER) e as empresas usuárias
-- (ADMIN), como a M2 Equipamentos. Cada usuário é dono de uma CONTA: a própria
-- base de clientes (V5), serviços (V4) e templates de notificação (V9).
-- Os clientes de uma conta NÃO são usuários: não fazem login.
-- Depende de: nada.
-- =============================================================================

-- MASTER: equipe BV2 — opera qualquer conta e gerencia os usuários.
-- ADMIN: empresa usuária — opera só a própria conta.
CREATE TYPE role_usuario AS ENUM ('MASTER', 'ADMIN');

CREATE TABLE usuarios (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome                VARCHAR(50)     NOT NULL,
    email               VARCHAR(50)     NOT NULL,
    senha               VARCHAR(255)    NOT NULL,   -- hash BCrypt
    criado_em           TIMESTAMP       NOT NULL DEFAULT NOW(),
    role                role_usuario    NOT NULL DEFAULT 'ADMIN',

    -- Usuário não se apaga: desativa-se, preservando o registro de quem operou
    -- o sistema.
    ativo               BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Momento da última troca de senha; invalida os JWT emitidos antes dele.
    -- NULL significa "nunca trocou" (os tokens existentes continuam válidos).
    -- A aplicação grava truncado a segundos, porque o "iat" do JWT é em
    -- segundos e a comparação com microssegundos derrubaria sessões legítimas.
    senha_alterada_em   TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);
