CREATE TABLE usuarios (
    id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR(50)     NOT NULL,
    email       VARCHAR(50)     NOT NULL,
    senha       VARCHAR(255)    NOT NULL,
    criado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);