--- Cada usuario passa a ter a propria base: clientes, servicos e templates de
--- notificacao ganham dono. O ADMIN so enxerga a conta dele; o MASTER escolhe em
--- qual conta opera (header X-Conta-Id).
---
--- O dono mora so nas tabelas raiz. equipamentos, ordens_servico, itens_os e
--- notificacoes herdam pelo cliente: gravar id_usuario nelas tambem abriria espaco
--- para um equipamento pertencer a um dono e o cliente dele a outro.
---
--- Dono dos dados que ja existem: o ADMIN mais antigo (a M2, que era quem operava
--- o sistema). Banco sem ADMIN cai no MASTER — em banco novo as tabelas estao
--- vazias e so os templates semeados na V18 recebem dono.
CREATE FUNCTION pg_temp.dono_padrao() RETURNS BIGINT AS $$
    SELECT COALESCE(
        (SELECT id FROM usuarios WHERE role = 'ADMIN' ORDER BY criado_em, id LIMIT 1),
        (SELECT id FROM usuarios WHERE role = 'MASTER' ORDER BY id LIMIT 1));
$$ LANGUAGE sql;

--- clientes -------------------------------------------------------------------
ALTER TABLE clientes ADD COLUMN id_usuario BIGINT;
UPDATE clientes SET id_usuario = pg_temp.dono_padrao();
ALTER TABLE clientes ALTER COLUMN id_usuario SET NOT NULL;
ALTER TABLE clientes
    ADD CONSTRAINT fk_clientes_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE RESTRICT;

--- Toda listagem passa a filtrar por dono, e as de equipamentos, OS e notificacoes
--- chegam ao dono pelo join com clientes.
CREATE INDEX idx_clientes_usuario ON clientes (id_usuario);

--- servicos -------------------------------------------------------------------
ALTER TABLE servicos ADD COLUMN id_usuario BIGINT;
UPDATE servicos SET id_usuario = pg_temp.dono_padrao();
ALTER TABLE servicos ALTER COLUMN id_usuario SET NOT NULL;
ALTER TABLE servicos
    ADD CONSTRAINT fk_servicos_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE RESTRICT;

--- A unicidade (nome, valor) da V15 passa a valer dentro de cada conta: duas contas
--- podem ter "Troca de tela" por 320. id_usuario na frente serve tambem de indice
--- para o filtro por dono.
DROP INDEX uq_servicos_nome_valor;
CREATE UNIQUE INDEX uq_servicos_usuario_nome_valor ON servicos (id_usuario, LOWER(nome), valor);

--- templates_notificacao ------------------------------------------------------
--- A PK deixa de ser o status: agora e uma linha por (conta, status). Id surrogate
--- em vez de PK composta para a entidade JPA continuar simples.
ALTER TABLE templates_notificacao DROP CONSTRAINT pk_templates_notificacao;
ALTER TABLE templates_notificacao
    ADD COLUMN id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE templates_notificacao ADD CONSTRAINT pk_templates_notificacao PRIMARY KEY (id);

ALTER TABLE templates_notificacao ADD COLUMN id_usuario BIGINT;
UPDATE templates_notificacao SET id_usuario = pg_temp.dono_padrao();
ALTER TABLE templates_notificacao ALTER COLUMN id_usuario SET NOT NULL;
ALTER TABLE templates_notificacao
    ADD CONSTRAINT fk_templates_notificacao_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE RESTRICT;
ALTER TABLE templates_notificacao
    ADD CONSTRAINT uq_templates_notificacao_usuario_status UNIQUE (id_usuario, status);

--- As linhas atuais ficam com o dono padrao, com o ativo que tinham. As demais
--- contas recebem o mesmo texto, desligado: ninguem passa a mandar WhatsApp por
--- ter ganhado uma conta. Usuarios criados daqui em diante recebem os templates
--- pelo UsuarioService (TemplatesNotificacaoPadrao).
INSERT INTO templates_notificacao (id_usuario, status, conteudo, ativo)
SELECT u.id, t.status, t.conteudo, FALSE
FROM usuarios u
CROSS JOIN templates_notificacao t
WHERE t.id_usuario = pg_temp.dono_padrao()
  AND u.id <> pg_temp.dono_padrao();
