CREATE TABLE marcas (
    id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR(50)     NOT NULL,
    criado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_marcas PRIMARY KEY (id),
    CONSTRAINT uq_marcas_nome UNIQUE (nome)
);