-- =============================================================================
-- V2 — tokens_verificacao
-- Tokens de uso único enviados por e-mail: recuperação de senha e confirmação
-- de alteração de e-mail. Um único mecanismo (hash, expiração, uso único e
-- invalidação em cascata) atende as duas finalidades.
-- Depende de: usuarios (V1).
-- =============================================================================

CREATE TYPE finalidade_token AS ENUM ('RECUPERACAO_SENHA', 'ALTERACAO_EMAIL');

CREATE TABLE tokens_verificacao (
    id          BIGINT              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  BIGINT              NOT NULL,

    -- SHA-256 do token, nunca o token em si: um vazamento do banco não pode
    -- virar tomada de contas. SHA-256 e não BCrypt porque o token já nasce com
    -- 256 bits de entropia e precisa ser buscável por igualdade.
    token_hash  VARCHAR(64)         NOT NULL,

    expira_em   TIMESTAMP           NOT NULL,
    usado_em    TIMESTAMP,                      -- NULL = pendente
    criado_em   TIMESTAMP           NOT NULL DEFAULT NOW(),

    -- Sem default de propósito: todo insert precisa declarar a finalidade.
    finalidade  finalidade_token    NOT NULL,

    -- Endereço novo, só em tokens de ALTERACAO_EMAIL (NULL na recuperação de
    -- senha). Viaja no token para a tela de confirmação só precisar do link.
    email_novo  VARCHAR(50),

    CONSTRAINT pk_token_verificacao PRIMARY KEY (id),
    CONSTRAINT uq_token_verificacao_hash UNIQUE (token_hash),
    CONSTRAINT fk_token_verificacao_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT
);

-- O histórico é mantido: dá para auditar quantos links foram pedidos e quais
-- viraram troca de fato.
CREATE INDEX idx_tokens_verificacao_usuario ON tokens_verificacao (id_usuario);

-- Invalidação em cascata filtra por finalidade: pedir troca de e-mail não pode
-- matar um link de recuperação de senha recém-pedido. O índice parcial cobre
-- exatamente essa consulta (tokens ainda pendentes).
CREATE INDEX idx_tokens_verificacao_usuario_finalidade
    ON tokens_verificacao (id_usuario, finalidade) WHERE usado_em IS NULL;
