CREATE TABLE servicos (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(50)       NOT NULL,
    descricao       VARCHAR(500),
    valor           NUMERIC(9, 2)  NOT NULL,
    contador_uso    INTEGER         NOT NULL DEFAULT 0,
    ativo           BOOLEAN         NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_servicos PRIMARY KEY (id),
    CONSTRAINT chk_servicos_valor_positivo CHECK (valor >= 0),
    CONSTRAINT chk_servicos_contador_uso_positivo CHECK (contador_uso >= 0)
);