CREATE TABLE clientes (
    id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  BIGINT            NOT NULL,
    nome        VARCHAR(50)     NOT NULL,
    telefone    VARCHAR(13)     NOT NULL,
    ativo       BOOLEAN         NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT fk_clientes_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_clientes_id_usuario UNIQUE (id_usuario)
);