-- =============================================================================
-- V4 — servicos
-- Catálogo de serviços de uma conta, com o preço de tabela.
-- Depende de: usuarios (V1).
-- =============================================================================

CREATE TABLE servicos (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      BIGINT          NOT NULL,   -- conta dona do catálogo
    nome            VARCHAR(50)     NOT NULL,
    descricao       VARCHAR(500),
    valor           NUMERIC(9, 2)   NOT NULL,
    contador_uso    INTEGER         NOT NULL DEFAULT 0,
    ativo           BOOLEAN         NOT NULL DEFAULT TRUE,   -- desativa em vez de apagar
    criado_em       TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_servicos PRIMARY KEY (id),
    CONSTRAINT fk_servicos_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_servicos_valor_positivo CHECK (valor >= 0),
    CONSTRAINT chk_servicos_contador_uso_positivo CHECK (contador_uso >= 0)
);

-- Dentro de uma conta não pode haver dois serviços com o mesmo par (nome,
-- valor): "Troca de tela" por 450 e por 320 convivem, duas "Troca de tela" por
-- 320 não. Contas diferentes podem repetir o par.
-- LOWER(nome) torna a regra case-insensitive, igual à checagem do ServicoService.
-- id_usuario na frente faz o índice servir também ao filtro por conta.
CREATE UNIQUE INDEX uq_servicos_usuario_nome_valor ON servicos (id_usuario, LOWER(nome), valor);
