CREATE TABLE equipamentos (
    id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente  BIGINT            NOT NULL,
    id_marca    BIGINT            NOT NULL,
    nome      VARCHAR(50)     NOT NULL,
    criado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_equipamentos PRIMARY KEY (id),
    CONSTRAINT fk_equipamentos_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_equipamentos_marca
        FOREIGN KEY (id_marca)
        REFERENCES marcas (id)
        ON DELETE RESTRICT
);