-- =============================================================================
-- V5 — clientes
-- Clientes de uma conta: quem leva o equipamento para consertar. É um cadastro,
-- não um usuário do sistema — cliente não faz login.
--
-- O dono (id_usuario) mora aqui e não se repete em equipamentos, ordens_servico,
-- itens_os e notificacoes: essas tabelas herdam a conta pelo cliente. Gravar o
-- dono nelas abriria espaço para um equipamento pertencer a uma conta e o cliente
-- dele a outra.
-- Depende de: usuarios (V1).
-- =============================================================================

CREATE TABLE clientes (
    id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  BIGINT          NOT NULL,   -- conta dona do cliente
    nome        VARCHAR(50)     NOT NULL,
    telefone    VARCHAR(13)     NOT NULL,   -- usado no envio de WhatsApp
    ativo       BOOLEAN         NOT NULL DEFAULT TRUE,   -- desativa em vez de apagar
    criado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_clientes PRIMARY KEY (id),
    CONSTRAINT fk_clientes_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT
);

-- Toda listagem filtra por conta, e as de equipamentos, OS e notificações chegam
-- à conta pelo join com clientes.
CREATE INDEX idx_clientes_usuario ON clientes (id_usuario);
