--- cria o enum
CREATE TYPE status_os AS ENUM ('EM_ANDAMENTO', 'CONCLUIDA', 'ENTREGUE', 'CANCELADA');

--- estrutura da tabela
CREATE TABLE ordens_servico (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      BIGINT          NOT NULL,
    observacao      VARCHAR(500),
    status          status_os       NOT NULL DEFAULT 'EM_ANDAMENTO',
    data_entrada    DATE            NOT NULL DEFAULT CURRENT_DATE,
    data_concluida  DATE,
    data_entregue   DATE,
    valor_total     NUMERIC(9,2)    NOT NULL,
    criado_em       TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_ordem_servico PRIMARY KEY (id),
    CONSTRAINT fk_ordem_servico_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id)
        ON DELETE RESTRICT,

    -- data_concluida nunca pode ser antes da data_entrada
    CONSTRAINT chk_data_concluida
        CHECK (data_concluida IS NULL OR data_concluida >= data_entrada),

    -- data_entregue nunca pode ser antes da data_entrada
    CONSTRAINT chk_data_entregue_entrada
        CHECK (data_entregue IS NULL OR data_entregue >= data_entrada),

    -- data_entregue nunca pode ser antes de data_concluida
    CONSTRAINT chk_data_entregue_concluida
        CHECK (data_entregue IS NULL OR data_concluida IS NULL OR data_entregue >= data_concluida)
);

--- função do trigger
CREATE OR REPLACE FUNCTION fn_atualizar_datas_os()
RETURNS TRIGGER AS $$
BEGIN
    -- Preenche data_concluida automaticamente ao marcar CONCLUIDA
    IF NEW.status = 'CONCLUIDA' AND OLD.status <> 'CONCLUIDA' THEN
        NEW.data_concluida := CURRENT_DATE;
    END IF;

    -- Preenche data_entregue automaticamente ao marcar ENTREGUE
    IF NEW.status = 'ENTREGUE' AND OLD.status <> 'ENTREGUE' THEN
        NEW.data_entregue := CURRENT_DATE;
    END IF;

    -- Impede marcar ENTREGUE sem ter passado por CONCLUIDA antes
    IF NEW.status = 'ENTREGUE' AND OLD.status = 'EM_ANDAMENTO' THEN
        RAISE EXCEPTION 'OS não pode ser marcada como ENTREGUE sem antes ser CONCLUIDA.';
    END IF;

    -- Impede reabrir uma OS já entregue
    IF OLD.status = 'ENTREGUE' AND NEW.status <> 'ENTREGUE' THEN
        RAISE EXCEPTION 'OS já entregue não pode ter o status alterado.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--- trigger
CREATE TRIGGER trg_datas_os
BEFORE UPDATE OF status ON ordens_servico
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_datas_os();