-- =============================================================================
-- V6 — equipamentos
-- Equipamentos de cada cliente (a furadeira, a serra...), sempre de uma marca.
-- Depende de: clientes (V5), marcas (V3).
-- =============================================================================

CREATE TABLE equipamentos (
    id          BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente  BIGINT          NOT NULL,
    id_marca    BIGINT          NOT NULL,
    nome        VARCHAR(50)     NOT NULL,
    criado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_equipamentos PRIMARY KEY (id),
    CONSTRAINT fk_equipamentos_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_equipamentos_marca
        FOREIGN KEY (id_marca)
        REFERENCES marcas (id)
        ON DELETE RESTRICT
);

-- O mesmo cliente não pode ter dois equipamentos com o mesmo nome E a mesma
-- marca: na hora de abrir a OS não daria para distinguir "Furadeira Makita" de
-- "Furadeira Makita". Nome igual com outra marca, ou em outro cliente, vale.
-- LOWER(nome) torna a regra case-insensitive, igual à checagem do
-- EquipamentoService.
CREATE UNIQUE INDEX uq_equipamentos_cliente_marca_nome
    ON equipamentos (id_cliente, id_marca, LOWER(nome));

-- O Postgres não indexa FK sozinho. Atende o ranking de marcas do painel
-- (itens_os -> equipamentos -> marcas) e o ON DELETE RESTRICT de marcas.
-- id_cliente já é a coluna líder do índice único acima.
CREATE INDEX idx_equipamentos_marca ON equipamentos (id_marca);
