CREATE TABLE itens_os (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_ordem_servico    BIGINT            NOT NULL,
    id_equipamento      BIGINT            NOT NULL,
    id_servico          BIGINT            NOT NULL,
    observacao          VARCHAR(500),
    criado_em           TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_item_os PRIMARY KEY (id),
    CONSTRAINT fk_item_os_ordem_servico
        FOREIGN KEY (id_ordem_servico)
        REFERENCES ordens_servico (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_item_os_equipamento
        FOREIGN KEY (id_equipamento)
        REFERENCES equipamentos (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_item_os_servico
        FOREIGN KEY (id_servico)
        REFERENCES servicos (id)
        ON DELETE RESTRICT,
    -- evita duplicidade de serviço para o mesmo equipamento dentro de uma OS
    CONSTRAINT uq_item_os_os_equip_servico UNIQUE (id_ordem_servico, id_equipamento, id_servico)
);