-- =============================================================================
-- V7 — ordens_servico
-- Ordem de serviço (OS) aberta para um cliente. Os serviços executados ficam
-- em itens_os (V8). O ciclo de vida do status é protegido por trigger.
-- Depende de: clientes (V5).
-- =============================================================================

-- Fluxo: EM_ANDAMENTO -> CONCLUIDA -> ENTREGUE (terminal). CANCELADA a qualquer
-- momento antes da entrega.
CREATE TYPE status_os AS ENUM ('EM_ANDAMENTO', 'CONCLUIDA', 'ENTREGUE', 'CANCELADA');

CREATE TABLE ordens_servico (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente          BIGINT          NOT NULL,
    observacao          VARCHAR(500),
    status              status_os       NOT NULL DEFAULT 'EM_ANDAMENTO',
    data_entrada        DATE            NOT NULL DEFAULT CURRENT_DATE,
    data_concluida      DATE,           -- preenchida pelo trigger
    data_entregue       DATE,           -- preenchida pelo trigger
    valor_total         NUMERIC(9,2)    NOT NULL,
    criado_em           TIMESTAMP       NOT NULL DEFAULT NOW(),

    -- TRUE quando o valor_total foi definido à mão (desconto, preço fechado) e
    -- deixa de ser recalculado pelos itens. Um reset volta para FALSE e o valor
    -- passa a refletir a soma dos serviços de novo.
    valor_total_manual  BOOLEAN         NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_ordem_servico PRIMARY KEY (id),
    CONSTRAINT fk_ordem_servico_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id)
        ON DELETE RESTRICT,

    -- data_concluida nunca pode ser antes da data_entrada
    CONSTRAINT chk_data_concluida
        CHECK (data_concluida IS NULL OR data_concluida >= data_entrada),

    -- data_entregue nunca pode ser antes da data_entrada
    CONSTRAINT chk_data_entregue_entrada
        CHECK (data_entregue IS NULL OR data_entregue >= data_entrada),

    -- data_entregue nunca pode ser antes de data_concluida
    CONSTRAINT chk_data_entregue_concluida
        CHECK (data_entregue IS NULL OR data_concluida IS NULL OR data_entregue >= data_concluida)
);

-- -----------------------------------------------------------------------------
-- Índices (painel e filtros de GET /ordens-servico)
-- -----------------------------------------------------------------------------

-- Série mensal, faturamento em aberto, rankings e o filtro ?dataInicio=.
CREATE INDEX idx_ordens_servico_data_entrada ON ordens_servico (data_entrada);

-- Parcial de propósito: data_entregue só é preenchida ao virar ENTREGUE, que é
-- terminal. "data_entregue IS NOT NULL" equivale a "status = ENTREGUE", o recorte
-- exato do faturamento realizado.
CREATE INDEX idx_ordens_servico_data_entregue ON ordens_servico (data_entregue)
    WHERE data_entregue IS NOT NULL;

-- FK sem índice automático. Ranking de clientes e filtro ?clienteId=.
CREATE INDEX idx_ordens_servico_cliente ON ordens_servico (id_cliente);

-- -----------------------------------------------------------------------------
-- Trigger: datas automáticas e regras de transição de status
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_atualizar_datas_os()
RETURNS TRIGGER AS $$
BEGIN
    -- Preenche data_concluida automaticamente ao marcar CONCLUIDA
    IF NEW.status = 'CONCLUIDA' AND OLD.status <> 'CONCLUIDA' THEN
        NEW.data_concluida := CURRENT_DATE;
    END IF;

    -- Preenche data_entregue automaticamente ao marcar ENTREGUE
    IF NEW.status = 'ENTREGUE' AND OLD.status <> 'ENTREGUE' THEN
        NEW.data_entregue := CURRENT_DATE;
    END IF;

    -- Impede marcar ENTREGUE sem ter passado por CONCLUIDA antes
    IF NEW.status = 'ENTREGUE' AND OLD.status = 'EM_ANDAMENTO' THEN
        RAISE EXCEPTION 'OS não pode ser marcada como ENTREGUE sem antes ser CONCLUIDA.';
    END IF;

    -- Impede reabrir uma OS já entregue
    IF OLD.status = 'ENTREGUE' AND NEW.status <> 'ENTREGUE' THEN
        RAISE EXCEPTION 'OS já entregue não pode ter o status alterado.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_datas_os
BEFORE UPDATE OF status ON ordens_servico
FOR EACH ROW
EXECUTE FUNCTION fn_atualizar_datas_os();
