-- =============================================================================
-- V8 — itens_os
-- Cada linha é um serviço executado em um equipamento, dentro de uma OS.
-- Depende de: ordens_servico (V7), equipamentos (V6), servicos (V4).
-- =============================================================================

CREATE TABLE itens_os (
    id                  BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_ordem_servico    BIGINT          NOT NULL,
    id_equipamento      BIGINT          NOT NULL,
    id_servico          BIGINT          NOT NULL,
    observacao          VARCHAR(500),
    criado_em           TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_item_os PRIMARY KEY (id),
    CONSTRAINT fk_item_os_ordem_servico
        FOREIGN KEY (id_ordem_servico)
        REFERENCES ordens_servico (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_item_os_equipamento
        FOREIGN KEY (id_equipamento)
        REFERENCES equipamentos (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_item_os_servico
        FOREIGN KEY (id_servico)
        REFERENCES servicos (id)
        ON DELETE RESTRICT,
    -- evita duplicidade de serviço para o mesmo equipamento dentro de uma OS
    CONSTRAINT uq_item_os_os_equip_servico UNIQUE (id_ordem_servico, id_equipamento, id_servico)
);

-- Na UNIQUE acima id_ordem_servico é a coluna líder; id_servico e id_equipamento
-- sozinhos ficam descobertos. Estes índices atendem o ranking de serviços do
-- painel e o ON DELETE RESTRICT ao excluir serviço ou equipamento.
CREATE INDEX idx_itens_os_servico ON itens_os (id_servico);
CREATE INDEX idx_itens_os_equipamento ON itens_os (id_equipamento);
