CREATE TYPE tipo_notificacao AS ENUM ('PRAZO_INICIADO', 'PRAZO_ENCERRADO', 'PERSONALIZADO');
CREATE TYPE status_notificacao AS ENUM ('PENDENTE', 'ENVIADO', 'FALHOU');

CREATE TABLE notificacoes (
    id                  BIGINT                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_ordem_servico    BIGINT                  NOT NULL,
    id_cliente          BIGINT                  NOT NULL,
    tipo                tipo_notificacao        NOT NULL,
    conteudo            VARCHAR(500)            NOT NULL,
    status              status_notificacao      NOT NULL DEFAULT 'PENDENTE',
    tentativas          INTEGER                 NOT NULL DEFAULT 0,
    data_envio          TIMESTAMP,
    criado_em           TIMESTAMP               NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_notificacao PRIMARY KEY (id),
    CONSTRAINT fk_notificacao_ordem_servico
        FOREIGN KEY (id_ordem_servico)
        REFERENCES ordens_servico (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_notificacao_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_notificacao_tentativas
        CHECK (tentativas >= 0)
);