-- =============================================================================
-- V9 — templates_notificacao
-- Configuração das mensagens de WhatsApp de cada conta: uma linha por
-- (conta, status de OS que notifica o cliente). O conteúdo inicial é inserido
-- em V12 para as contas existentes; usuários criados depois recebem os seus
-- pela aplicação (UsuarioService).
-- Depende de: usuarios (V1), enum status_os (V7).
-- =============================================================================

CREATE TABLE templates_notificacao (
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      BIGINT          NOT NULL,   -- conta dona da configuração

    -- Notificar um status novo é um INSERT, não uma migration de enum.
    status          status_os       NOT NULL,

    -- Texto com placeholders {cliente}, {os} e {valor}.
    conteudo        VARCHAR(500)    NOT NULL,

    ativo           BOOLEAN         NOT NULL DEFAULT FALSE,
    atualizado_em   TIMESTAMP       NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_templates_notificacao PRIMARY KEY (id),
    CONSTRAINT fk_templates_notificacao_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_templates_notificacao_usuario_status UNIQUE (id_usuario, status)
);
